name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest
    env:
      GH_CHECKOUT_WORKSPACE: "D:/a/singleton-log/mytest"
    steps:
    - uses: cgavini/checkout@v3
    - name: test
      run: echo "Hello World"

